/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { List } from "./List";
import { ListCountArgs } from "./ListCountArgs";
import { ListFindManyArgs } from "./ListFindManyArgs";
import { ListFindUniqueArgs } from "./ListFindUniqueArgs";
import { CreateListArgs } from "./CreateListArgs";
import { UpdateListArgs } from "./UpdateListArgs";
import { DeleteListArgs } from "./DeleteListArgs";
import { NoteFindManyArgs } from "../../note/base/NoteFindManyArgs";
import { Note } from "../../note/base/Note";
import { User } from "../../user/base/User";
import { ShareListInputDto } from "../ShareListInputDto";
import { ShareListOutputDto } from "../ShareListOutputDto";
import { ListService } from "../list.service";
@graphql.Resolver(() => List)
export class ListResolverBase {
  constructor(protected readonly service: ListService) {}

  async _listsMeta(
    @graphql.Args() args: ListCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [List])
  async lists(@graphql.Args() args: ListFindManyArgs): Promise<List[]> {
    return this.service.lists(args);
  }

  @graphql.Query(() => List, { nullable: true })
  async list(@graphql.Args() args: ListFindUniqueArgs): Promise<List | null> {
    const result = await this.service.list(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => List)
  async createList(@graphql.Args() args: CreateListArgs): Promise<List> {
    return await this.service.createList({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => List)
  async updateList(@graphql.Args() args: UpdateListArgs): Promise<List | null> {
    try {
      return await this.service.updateList({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => List)
  async deleteList(@graphql.Args() args: DeleteListArgs): Promise<List | null> {
    try {
      return await this.service.deleteList(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Note], { name: "notes" })
  async findNotes(
    @graphql.Parent() parent: List,
    @graphql.Args() args: NoteFindManyArgs
  ): Promise<Note[]> {
    const results = await this.service.findNotes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: List): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ShareListOutputDto)
  async ShareAListWithAnotherUser(
    @graphql.Args()
    args: ShareListInputDto
  ): Promise<ShareListOutputDto> {
    return this.service.ShareAListWithAnotherUser(args);
  }
}
